#!/usr/bin/env python3
"""
Arduino COM Port Configuration Helper
This script helps detect available COM ports and configure the Arduino connection.
"""

import serial.tools.list_ports
import platform
import sys
import os

def detect_available_ports():
    """Detect available serial ports"""
    print("Scanning for available serial ports...")
    print("=" * 50)
    
    ports = serial.tools.list_ports.comports()
    available_ports = []
    
    for i, port in enumerate(ports, 1):
        port_info = f"{i}. {port.device} - {port.description}"
        if port.manufacturer:
            port_info += f" ({port.manufacturer})"
        print(port_info)
        available_ports.append(port.device)
    
    if not available_ports:
        print("No serial ports found!")
        return None
    
    return available_ports

def suggest_arduino_port(ports):
    """Suggest the most likely Arduino port"""
    if not ports:
        return None
    
    # Look for Arduino-specific keywords
    arduino_keywords = ['arduino', 'ch340', 'cp210x', 'ftdi', 'usb-serial']
    
    for port in ports:
        port_info = port.lower()
        for keyword in arduino_keywords:
            if keyword in port_info:
                return port
    
    # If no Arduino-specific port found, return the first port
    return ports[0]

def update_server_config(port):
    """Update the server configuration with the selected port"""
    config_file = os.path.join(os.path.dirname(__file__), 'arduino_config.py')
    
    config_content = f'''# Arduino COM Port Configuration
# This file is automatically generated by the port configuration helper

ARDUINO_PORT = "{port}"

# You can also manually set this in your main.py by modifying:
# arduino_comm = ArduinoCommunicator(port="{port}")
'''
    
    with open(config_file, 'w') as f:
        f.write(config_content)
    
    print(f"\nConfiguration saved to: {config_file}")
    print(f"Arduino port set to: {port}")

def main():
    print("Arduino COM Port Configuration Helper")
    print("=" * 50)
    
    # Detect available ports
    available_ports = detect_available_ports()
    
    if not available_ports:
        print("\nNo serial ports detected. Please check:")
        print("1. Arduino is connected via USB")
        print("2. USB drivers are installed")
        print("3. Arduino is powered on")
        return
    
    # Suggest Arduino port
    suggested_port = suggest_arduino_port(available_ports)
    print(f"\nSuggested Arduino port: {suggested_port}")
    
    # Get user selection
    while True:
        try:
            choice = input(f"\nSelect port (1-{len(available_ports)}) or press Enter for suggested port: ").strip()
            
            if not choice:
                selected_port = suggested_port
                break
            else:
                choice_num = int(choice)
                if 1 <= choice_num <= len(available_ports):
                    selected_port = available_ports[choice_num - 1]
                    break
                else:
                    print("Invalid selection. Please try again.")
        except ValueError:
            print("Please enter a valid number.")
    
    print(f"\nSelected port: {selected_port}")
    
    # Update configuration
    update_server_config(selected_port)
    
    # Provide next steps
    print("\nNext steps:")
    print("1. Restart the Python server: python main.py")
    print("2. Open the web interface: http://localhost:8000")
    print("3. Check the Arduino port status in the System Status section")
    
    # Test connection
    print(f"\nTesting connection to {selected_port}...")
    try:
        ser = serial.Serial(selected_port, 115200, timeout=2)
        print("✅ Port opened successfully!")
        ser.close()
    except Exception as e:
        print(f"❌ Connection test failed: {e}")
        print("Make sure the Arduino is connected and the sketch is running.")

if __name__ == "__main__":
    main()
