"""
Constants for turbulence controller system
All magic numbers and configuration values should be defined here
"""
from enum import Enum


class ResponseStatus(str, Enum):
    """Standard response status strings"""
    SUCCESS = "success"
    ERROR = "error"
    OK = "ok"
    FAIL = "fail"


class DeviceStatus(str, Enum):
    """Device status strings"""
    ONLINE = "online"
    OFFLINE = "offline"
    ERROR = "error"
    UNKNOWN = "unknown"


# Arduino Communication Constants
ARDUINO_DEFAULT_BAUDRATE = 1000000
ARDUINO_COM_PORT_START = 4
ARDUINO_COM_PORT_END = 10
ARDUINO_DEFAULT_COM_PORT = "COM4"
ARDUINO_LINUX_PORT = "/dev/ttyACM0"
ARDUINO_TIMEOUT = 2.0
ARDUINO_WRITE_TIMEOUT = 2.0
ARDUINO_INIT_DELAY = 3.0
ARDUINO_MAX_FAILURES = 3
ARDUINO_CONNECTION_CHECK_INTERVAL = 5.0
ARDUINO_READ_TIMEOUT = 10.0
ARDUINO_READ_SIZE_LIMIT = 1024

# Camera Constants
CAMERA_IMAGES_FOLDER = "camera_images"
CAMERA_FRAME_QUEUE_SIZE = 10
CAMERA_RETRIEVE_TIMEOUT = 5000
CAMERA_FILENAME_FORMAT = "camera_%Y%m%d_%H%M%S_%f"
CAMERA_VIDEO_FRAME_DELAY = 0.033
CAMERA_JPEG_QUALITY = 85
CAMERA_IMAGE_EXTENSION = ".png"

# WebSocket Constants
WS_RECONNECT_DELAY = 3000
WS_STATUS_ENDPOINT = "/ws/status"
WS_VIDEO_ENDPOINT = "/ws/video"
WS_MESSAGE_TYPE_PING = "ping"
WS_MESSAGE_TYPE_PONG = "pong"
WS_MESSAGE_TYPE_START_STREAM = "start_stream"
WS_MESSAGE_TYPE_STOP_STREAM = "stop_stream"

# Threshold Constants
TEMPERATURE_WARNING_THRESHOLD = 60
TEMPERATURE_DANGER_THRESHOLD = 80
TEMPERATURE_SENSOR_NORMAL = 20
TEMPERATURE_SENSOR_WARNING = 30
TEMPERATURE_INVALID_THRESHOLD = -100
HUMIDITY_VALID_THRESHOLD = 0

# Fan Constants
FAN_SPEED_MIN = 0
FAN_SPEED_MAX = 255
FAN_DURATION_MIN = 0.5
FAN_DURATION_MAX = 5.0
FAN_DURATION_CALCULATION_FACTOR = 4.5
FAN_SLIDER_MIN = -20
FAN_SLIDER_MAX = 40
FAN_SLIDER_RANGE = 60
FAN_SLIDER_CENTER = 40

# Hot Plate Constants
HOT_PLATE_ID_MIN = 0
HOT_PLATE_ID_MAX = 1
HOT_PLATE_SWITCH_KNOB_OFF = 10
HOT_PLATE_SWITCH_KNOB_ON = 30

# Data Capture Constants
CENTROID_HISTORY_THRESHOLD = 30
DATA_CAPTURE_FOLDER_DATE_FORMAT = "%d_%b_%Y"
DATA_CAPTURE_FOLDER_TIME_FORMAT = "%H_%M"
MAX_HISTORY_SIZE = 1000
POLLING_INTERVAL_DEFAULT = 1.0

# Calibration Constants
CALIBRATION_WINDFLOW_FAN_SPEED_STEP_DEFAULT = 5
CALIBRATION_WINDFLOW_SETTLING_TIME_DEFAULT = 1000
CALIBRATION_WINDFLOW_NUM_SAMPLES_DEFAULT = 3
CALIBRATION_HOTPLATE_TEMP_MIN_DEFAULT = 80.0
CALIBRATION_HOTPLATE_TEMP_MAX_DEFAULT = 120.0
CALIBRATION_HOTPLATE_TEMP_STEP_DEFAULT = 2.0
CALIBRATION_HOTPLATE_FAN_SPEEDS_DEFAULT = "255,191,128,64"
CALIBRATION_HOTPLATE_RECORDING_DURATION_DEFAULT = 900
CALIBRATION_HOTPLATE_SAMPLING_INTERVAL_DEFAULT = 10

# Image Processing Constants
IMAGE_THRESHOLD_DEFAULT = 20
IMAGE_ADAPTIVE_THRESHOLD_BLOCK_SIZE = 11
IMAGE_ADAPTIVE_THRESHOLD_C = 2
IMAGE_EPSILON = 1e-16
IMAGE_CENTROID_DEFAULT = (0, 0)

# UI Constants
UI_NOTIFICATION_TIMEOUT = 5000
UI_CLIENT_ID_LENGTH = 36
UI_CLIENT_ID_START = 2
UI_CLIENT_ID_SUBSTR = 9

# Color Constants
COLOR_SUCCESS = "#28a745"
COLOR_DANGER = "#dc3545"
COLOR_WARNING = "#ffc107"
COLOR_INFO = "#17a2b8"
COLOR_HOTPLATE_ON = "#ff6b6b"
COLOR_HOTPLATE_ON_STROKE = "#ff4444"
COLOR_HOTPLATE_OFF = "#c0c0c0"
COLOR_HOTPLATE_OFF_STROKE = "#333"
COLOR_SWITCH_ON = "#28a745"
COLOR_SWITCH_ON_STROKE = "#1e7e34"
COLOR_SWITCH_OFF = "#fff"
COLOR_SWITCH_OFF_STROKE = "#999"

# API Endpoint Constants
API_BASE = "/api"
API_STATUS = f"{API_BASE}/status"
API_TEMPERATURE_SET = f"{API_BASE}/temperature/set"
API_FAN_SET = f"{API_BASE}/fan/set"
API_HOTPLATE_TOGGLE = f"{API_BASE}/hotplate"
API_SETTINGS = f"{API_BASE}/settings"
API_SETTINGS_APPLY = f"{API_BASE}/settings/apply"
API_CAMERA_STATUS = f"{API_BASE}/camera/status"
API_CAMERA_VIDEO_STOP = f"{API_BASE}/camera/video/stop"
API_CALIBRATION_WINDFLOW_START = f"{API_BASE}/calibration/windflow/start"
API_CALIBRATION_CONTROL = f"{API_BASE}/calibration/control"
API_CALIBRATION_SESSION = f"{API_BASE}/calibration/session"
API_CALIBRATION_SESSION_CLEAR = f"{API_BASE}/calibration/session/clear"
API_CALIBRATION_HOTPLATE_START = f"{API_BASE}/calibration/hotplate/start"
API_CALIBRATION_LOOKUP_TABLE = f"{API_BASE}/calibration/lookup-table"
API_CALIBRATION_LOOKUP_TABLE_INTERPOLATE = f"{API_BASE}/calibration/lookup-table/interpolate"
API_CALIBRATION_WINDFLOW_POLYNOMIALS = f"{API_BASE}/calibration/windflow-polynomials"

# CN² Constants
CN2_ROW1_500_INDEX = 0
CN2_ROW1_300_INDEX = 1
CN2_ROW2_500_INDEX = 2
CN2_ROW2_300_INDEX = 3
